
#ifndef VTKGUISUPPORTQTOPENGL_EXPORT_H
#define VTKGUISUPPORTQTOPENGL_EXPORT_H

#ifdef VTKGUISUPPORTQTOPENGL_STATIC_DEFINE
#  define VTKGUISUPPORTQTOPENGL_EXPORT
#  define VTKGUISUPPORTQTOPENGL_NO_EXPORT
#else
#  ifndef VTKGUISUPPORTQTOPENGL_EXPORT
#    ifdef GUISupportQtOpenGL_EXPORTS
        /* We are building this library */
#      define VTKGUISUPPORTQTOPENGL_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKGUISUPPORTQTOPENGL_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKGUISUPPORTQTOPENGL_NO_EXPORT
#    define VTKGUISUPPORTQTOPENGL_NO_EXPORT 
#  endif
#endif

#ifndef VTKGUISUPPORTQTOPENGL_DEPRECATED
#  define VTKGUISUPPORTQTOPENGL_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKGUISUPPORTQTOPENGL_DEPRECATED_EXPORT
#  define VTKGUISUPPORTQTOPENGL_DEPRECATED_EXPORT VTKGUISUPPORTQTOPENGL_EXPORT VTKGUISUPPORTQTOPENGL_DEPRECATED
#endif

#ifndef VTKGUISUPPORTQTOPENGL_DEPRECATED_NO_EXPORT
#  define VTKGUISUPPORTQTOPENGL_DEPRECATED_NO_EXPORT VTKGUISUPPORTQTOPENGL_NO_EXPORT VTKGUISUPPORTQTOPENGL_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKGUISUPPORTQTOPENGL_NO_DEPRECATED
#    define VTKGUISUPPORTQTOPENGL_NO_DEPRECATED
#  endif
#endif

#endif /* VTKGUISUPPORTQTOPENGL_EXPORT_H */
